### ISSUE TITLE
Links redirect from HTTPS:// to HTTP://

### ISSUE THREAD

**Issue by IsmailM** [wurmlab/wurmlab.github.io#13]
This is a change in the config file…

I suggest this because `{{site.url }}` currently defaults to http:// despite whether or not http:// or https:// is used.

As a result, if you are viewing the website at [https://wurmlab.github.io](https://wurmlab.github.io), the links in the header takes you to the http:// links…

BTW: using HTTPS has a major impact on SEO according to Google

**Comment by bmpvieira** [comment]
Maybe try ```//wurmlab.github.io```, sometimes it works (i.e., will link to either http or https depending on where you are when you click. This may need to be applied to all links.

**Comment by yannickwurm** [comment]
is this resolved?

**Comment by IsmailM** [comment]
Nope, not yet. I remember trying quite a few obvious solutions but it didn’t work at the time…

I’ll have another look when I get a chance

**Comment by yeban** [comment]
This is done, I think.
