### ISSUE TITLE
haplodiploid simulation paper is missing - please add

### ISSUE THREAD

**Issue by yannickwurm** [wurmlab/wurmlab.github.io#141]
- add: https://academic.oup.com/gbe/article/14/5/evac062/6576481?login=true - primary research
 - update Reference and DOI changed for: Genomic signatures of recent adaptation in a wild bumblebee
https://academic.oup.com/mbe/article-abstract/39/2/msab366/6521030
 - add https://www.sciencedirect.com/science/article/pii/S016953472100313X (with "ERGA Consortium" as only author) - as review  paper
 - add https://helda.helsinki.fi/bitstream/handle/10138/229390/The_global_2017.pdf?sequence=1 - with "GAGA consortium" as only author

**Comment by yannickwurm** [comment]
each of these is a different publication - 3 of them need to be added to the publication page from scratch; one of them just needs to be updated. Following the link should make it possible to see all required info

**Comment by yuriigr** [comment]
Done.
Commits: https://github.com/wurmlab/wurmlab.github.io/commit/13cf199a916c00a5f6572ee567d13c7d62739eba, https://github.com/wurmlab/wurmlab.github.io/commit/81c028a18c22f4ce7e5db1c48c306b148d4616dd
