### ISSUE TITLE
Is it possible to increase caching times for everything other than index, team and publications? 

### ISSUE THREAD

**Issue by yannickwurm** [wurmlab/wurmlab.github.io#155]
![Screenshot 2022-09-16 at 14 25 56](https://user-images.githubusercontent.com/150113/190649537-1584a697-aebe-4d40-879d-70ffb5645e39.png)

**Comment by yuriigr** [comment]
What service are you using for hosting? GitHub gh-pages?

**Comment by yannickwurm** [comment]
yes

**Comment by yuriigr** [comment]
Answer from GitHub support:

Thanks for reaching out to GitHub Support about using GitHub Pages

We set the following Cache-Control header for all GitHub Pages content:

Cache-Control: max-age=600

This header is the same for all assets on all sites on our Pages service, and we don't currently provide a way to alter the value.

I hope that this answers your questions.

**Comment by yuriigr** [comment]
We are not the first who is looking for this possibility. Sorry.
