### ISSUE TITLE
The markdown engine that we use is going to be deprecated on GitHub Pages from May 1st.

### ISSUE THREAD

**Issue by yeban** [wurmlab/wurmlab.github.io#16]
Just received the following notification from Github:

> You are currently using the 'rdiscount' Markdown engine, which will not be supported on GitHub Pages after May 1st. At that time, your site will use 'kramdown' for markdown rendering instead. To suppress this warning, remove the 'markdown' setting in your site's '_config.yml' file and confirm your site renders as expected. For more information, see https://help.github.com/articles/updating-your-markdown-processor-to-kramdown.

/cc @EmelineAurore

**Comment by yannickwurm** [comment]
so will this actually break anything?

**Comment by yeban** [comment]
Mostly no. Depends on if we are using any engine specific feature - somebody will have to take a look.

**Comment by yannickwurm** [comment]
I've made the change here: 9afa7bbe7a6575d47ddcf93b13f5ae745f3db055
so far nothing looks broken

**Comment by yeban** [comment]
Looks good to me too.
