### ISSUE TITLE
Advertise current PhD position

### ISSUE THREAD

**Issue by yannickwurm** [wurmlab/wurmlab.github.io#164]
Hi @yuriigr  - could you please add this to current open positions? 

https://www.linkedin.com/feed/update/urn:li:activity:7174456809313759232/

Thank you!
Yannick

**Comment by yuriigr** [comment]
![image](https://github.com/wurmlab/wurmlab.github.io/assets/23266423/42723242-97fc-427d-ad4b-4abef6d100d5)

Is this correct text and place?

**Comment by yannickwurm** [comment]
Yes perfect - can you please add a date, and can you please also cross out the other ones?




Yannick Wurm  - https://wurmlab.com<https://wurmlab.com/>
Professor in Evolutionary Genomics & Bioinformatics, Queen Mary University of London
Fellow, Alan Turing Institute for Data Science and Artificial Intelligence
Founder, Pragmatic Genomics https://sequenceserver.com<https://sequenceserver.com/>


On Sun, Mar 24, 2024 at 22:31:04, yuriigr ***@***.******@***.***>> wrote:

image.png (view on web)<https://github.com/wurmlab/wurmlab.github.io/assets/23266423/42723242-97fc-427d-ad4b-4abef6d100d5>

Is this correct text and place?

**Comment by yuriigr** [comment]
![image](https://github.com/wurmlab/wurmlab.github.io/assets/23266423/e6160096-6367-4d4a-bd50-6f11e2fc7e2c)
Done
