### ISSUE TITLE
calendar is lost?

### ISSUE THREAD

**Issue by yannickwurm** [wurmlab/wurmlab.github.io#19]
wurmlab.github.io/calendar.html is not found?

**Comment by yeban** [comment]
It's accessible at /calendar. I think this and #17 are related - something seems to have changed at our / GitHub's end that's causing /foo.html to be accessible only at /foo (e.g., @bmpvieira and @estolle's page).

**Comment by yannickwurm** [comment]
shit - can you guys please fix the internal links asap - this is really bad for our user xp

**Comment by yeban** [comment]
I grepped through the source and didn't find any reference to 'calendar.html' except in sitemap. So I guess all is good?

**Comment by yannickwurm** [comment]
fixed (hack) with 73cfbc809a6299177e627ccb1bb4353e4b92527f
