### ISSUE TITLE
Remote dependencies make offline development (e.g. while travelling) extremely challenging

### ISSUE THREAD

**Issue by yannickwurm** [wurmlab/wurmlab.github.io#29]
So perhaps we should include local copies of all libraries?

**Comment by IsmailM** [comment]
What do you mean by libraries -  ruby libraries (to run rake) or JS/CSS libraries?

**Comment by yannickwurm** [comment]
JS/CSS
Otherwise its extremely hard to judge (when developping/testing offline) whether what you did is a fixer or a breaker
