### ISSUE TITLE
some issues

### ISSUE THREAD

**Issue by yannickwurm** [wurmlab/wurmlab.github.io#32]
with new design:
- [ ] too much vertical whitespace on tools page
- [ ] too much vertical whitespace above headings on news page
- [ ] too much vertical whitespace on tools page
- [x] home page: too much whitespace on right side under map. Perhaps this can be filled with the stuff thats currently at the bottom. 
- [x] Navigation: publication -> Publication_s_
- [ ] home page: too much whitespace between sections
- [ ] home page: click on paragraph of relevant section should have same effect as clicking on "read more"
- [ ] home page: "read more" buttons mean we need a lot of whitespace - need a better solution.
- [x] home page: pollinator "read more" button for one line is an unnecessary complication

**Comment by yannickwurm** [comment]
- [ ] Yannick reword home page to have no "two word lines" after @IsmailM has done home page adjustments

**Comment by IsmailM** [comment]
Home Page:{
p: justify
image - remove right padding
}

remove the hr...

Contact -> change to 3
Main section -> Change to 9
Main Item -> change 8
Main Images -> change to 5


Add Recent News section - up to 5 items

**Comment by yannickwurm** [comment]
- [ ] home page right side: put "join the lab" as an h2 or h3 linking ot a new page. And itemized list of recent news items.
