### ISSUE TITLE
publications formatting

### ISSUE THREAD

**Issue by yannickwurm** [wurmlab/wurmlab.github.io#50]
Alignment of titles is heterogeneous (e.g. on the attached screenshot, the 3rd, 4th and penultimate publication are right-shifted by a space)

![screenshot 2017-06-02 11 41 48](https://cloud.githubusercontent.com/assets/150113/26722602/8f3ee610-4788-11e7-9ce7-17c4197ef774.png)

**Comment by EmelineAurore** [comment]
looks like it is fixed 
<img width="101" alt="screen shot 2017-09-11 at 18 37 25" src="https://user-images.githubusercontent.com/9661216/30288358-5be4cf9a-9720-11e7-9201-2708de05558f.png">
