### ISSUE TITLE
new blog posts needed

### ISSUE THREAD

**Issue by EmelineFavreau** [wurmlab/wurmlab.github.io#53]
blog posts needed. Please comment when you are planning to publish so we don't publish all at the same time, it will spoil the fun.
- [ ] New publication - can @MartinezRuiz-Carlos or @roddypr or @yannickwurm write a blob about this? This is the top priority, needs to happen very soon to keep the momentum
- [x] conferences and workshops over the last four months, can you do that @MartinezRuiz-Carlos ?
- [x] Google Summer of Code blog post from @aniarya82 ?
- [ ] Masters and Undergrad students - I will do this
- [ ] comparison of library preps - I will do this
- [ ] anything else?

**Comment by MartinezRuiz-Carlos** [comment]
I'll write something for the whole group. 
A post with short paragraphs for all conferences and workshops attended + who went there

**Comment by yannickwurm** [comment]
carlos I'm happy to revise what you've drafted

**Comment by aniarya82** [comment]
Hey, I have opened a PR [#55](https://github.com/wurmlab/wurmlab.github.io/pull/55) regarding the gsoc 2017 blog post.
Reviews are most welcome.
