### ISSUE TITLE
publication page: figure is hiding title of article

### ISSUE THREAD

**Issue by EmelineAurore** [wurmlab/wurmlab.github.io#69]
<img width="1006" alt="screen shot 2018-03-09 at 10 47 25" src="https://user-images.githubusercontent.com/9661216/37203981-76daa52e-2387-11e8-9d59-d518455fcd16.png">

**Comment by yannickwurm** [comment]
adding margin-left to the <img> was insufficient. Thus I had to put padding-right into the <li> instead. 
The resulting code is ugly ugly, but unless there is a way to keep variables in jekyll, I think its the best we can do.
