### ISSUE TITLE
Add GeneValidator to home page.

### ISSUE THREAD

**Issue by yeban** [wurmlab/wurmlab.github.io#7]
After SequenceServer and Afra, and before oswitch perhaps.

@IsmailM

**Comment by yannickwurm** [comment]
@yeban please add/move oSwitch mention to /tools  and update the seqserv photo.
I will soon rework the front page. 

@ismail can you update the genevalidator links and text on /tools ? Thanks

**Comment by ismail** [comment]
Wrong ismail :)

**Comment by yannickwurm** [comment]
haha sorry @ismail !
@IsmailM can *you*  update the genevalidator links and text on /tools ?

**Comment by yeban** [comment]
Merged @IsmailM's PR - I figured it would be good to have GV listed on homepage like other tools till you get around to working the home page and decide what to do with tools section.

Updated the tools page.
