### ISSUE TITLE
Need SSL certificate for when using wurmlab.com

### ISSUE THREAD

**Issue by yannickwurm** [wurmlab/wurmlab.github.io#91]
Probably following this:
https://help.dreamhost.com/hc/en-us/articles/215089118-Adding-an-SSL-certificate-overview

**Comment by yeban** [comment]
Are you sure? I mean, wurmlab.com simply redirects to https://wurmlab.github.io - so there shouldn't be a need for a SSL certificate?

**Comment by yannickwurm** [comment]
Github auto requests one when the DNS records are correct. 

It previously wasn't requesting one, because the DNS didn't have A and CNAME directives
