### ISSUE TITLE
browser caching?

### ISSUE THREAD

**Issue by yannickwurm** [wurmlab/wurmlab.github.io#92]
IIRC its currently set at 10 minutes

for everything other than html files it could be longer... e.g. 1 month. 
     https://developers.google.com/speed/docs/insights/LeverageBrowserCaching
     https://developers.google.com/web/fundamentals/performance/webpack/use-long-term-caching

**Comment by yeban** [comment]
Did you also come across a solution @yannickwurm? As far as I know, we can't change caching policy on GitHub Pages. We can use meta tag to specify cache expiration, but that would only work for HTML files and nothing else.
